Create helios-community-WL
ElrondNetwork/elrond-specs pull request #28
Opened 2022-11-23 18:24 UTC by KevinLydon

Transfer Whitelist request for the quarterly Helios Community LKMEX distribution.

2022-11-24 16:28 UTC, PABourdais commented
They will not accept it since you don't use a SC for LKMEX distribution

2022-11-25 09:51 UTC, sasurobert requested changes

2022-11-25 09:51 UTC, sasurobert commented on LKMEX-whitelist/helios-mitya-NFT-WL
> +erd1w3c0lqy8af6v27pq4qzn87t9glr33fk9qyym6mkye07gsn5xyanstvm0d9
We do not whitelist user addresses. Only SCs with well defined functions.

2022-11-25 09:51 UTC, sasurobert commented on LKMEX-whitelist/helios-community-WL
> +erd1w69k99shct7gdmalf7t3n9qedsv2cnn04lrc249trphydnr273dskvlnpp
We do not whitelist user addresses. Only SCs with well defined functions.

2022-12-22 14:16 UTC, sasurobert commented
Hello Helios Community,
After a thorough analysis of your Pull Request, we have concluded that we are unable to provide a ‘whitelisted’ status. The reasoning behind this decision is the fact that your project uses ‘wallets’ to send arbitrary amounts of XMEX and should it ever happen that the project’s keys are compromised or some illegitimate XMEX transfers are made, it would be difficult to detect and take action.
Our advice would be to create a proper NFT Staking Smart Contract where only the owner is allowed to deposit XMEX. Users can claim their rewards if they stake the NFT or by sending the NFT to the contract (thus proving that they own the NFT).
Have a productive day!

2022-12-22 14:16 UTC, closed without merging